### ISSUE TITLE
Bug - Interval continues to run after leaving page.

### ISSUE THREAD

**Issue by chungchunwang** [MartinPicc/budibase-interval-plugin#3]
Hi! First of all, thanks for making this plugin! I have found a small bug with it though, which is that the action linked to the interval continues to run even after navigating to a new page.

**Comment by chungchunwang** [comment]
I submitted a pull request which should fix this: #4 
I went in and added a couple of lines that deletes the interval in onDestroy(). This (at least in my tests) resolves the issue.

**Comment by MartinPicc** [comment]
Hi,
Thank you very much for contributing, looks all good to me, I merged your changes
